### ISSUE TITLE
Some users can't login

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#7] opened 2018-08-13 17:52 UTC
We have received reports that some users aren't able to login. This issue is to track those occurrences.

**Comment by caiosba** [comment] 2018-08-13 22:31
That's how I was able to reproduce it:

- Open an incognito window with two tabs: (1) https://montage.meedan.com and (2) https://greenday-project.appspot.com
- Login on tab (1)
- Reload tab (2): you should be logged in
- Sign out from tab (1)
- Reload tab (2): you should be logged out
- Try to login again on tab (1) or (2): you'll get the error

**Comment by caiosba** [comment] 2018-08-14 11:08
Actually it's simpler to reproduce:

- Open an incognito window with two tabs: (1) https://montage.meedan.com and (2) https://greenday-project.appspot.com
- Login on tab (1)
- Reload tab (2): you should be logged in
- Sign out from tab (1): You'll see an error
- Reload tab (2): you should be logged out and see an error too

**Comment by caiosba** [comment] 2018-08-14 11:35
Actually I was able to reproduce in a simpler way now...

- Open Montage in a tab
- Login
- Logout
- Login again: you'll get the error

**Comment by caiosba** [comment] 2018-08-14 11:38
Maybe related to this error:
`Refused to execute script from 'https://accounts.google.com/o/oauth2/revoke?token=...&callback=angular.callbacks._0' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

**Comment by caiosba** [comment] 2018-08-14 16:58
So, this is the problem:
- User logs in for the first time
- A token is received and is valid for some minutes
- Within that interval, no requests are made to Google backend: the token is cached
- User logs out: a request is made to Google's `revoke` endpoint
- User logs in again: if the expiration interval is not over, the cached token will be used - the local cache doesn't know that the `revoke` endpoint was called, but that token is not valid anymore - so the user is not able to log back in

I can confirm that this happens because no HTTP request is made to get a fresh token during the interval in which the token should be valid. Also, it works well in an incognito window. Need to find out where the token is cached (and it keeps cached even if the page is reloaded): I already verified it's not on `localStorage` or cookies.

**Comment by caiosba** [comment] 2018-08-15 16:07
I tried hard and for hours to be able to continue using `gapi.auth.authorize` for authentication, although this method is not encouraged by Google (from https://developers.google.com/identity/sign-in/web/reference#gapiauth2authorizeparams-callback):

> Warning: do not use this method alongside the recommended gapi.auth2.init and signIn flow. These 
> are two distinct behaviors (Authorization for gapi.auth2.authorize vs Authentication for 
> gapi.auth2.init/signIn) and will have unexpected issues if used within the same application.

Basically, the code was using for _authentication_ something that is for _authorization_ only. I tried many hacks to make it work for a real authentication flow, but didn't work.

I replaced the `auth.authorize` method by `auth2.signIn` for login and the manual way of logout (which is call the REST API `revoke` endpoint manually) by `auth2.signOut`. I didn't change the library version. Now everything works well. I pushed the code to a new branch. I'll test a little more, record a screencast, merge to `develop` and close this issue.

**Comment by caiosba** [comment] 2018-08-15 18:58
Merged. The fix is available on `develop`. This video shows the problem: https://www.youtube.com/watch?v=hnDDQkRmNXY. After we logout and refresh the page, we are still logged in for some seconds. Another refresh, and we are at the login page. But if we try to login, we can't, and we get a "Invalid token" error message. This other video shows that the flow works after the fix: https://www.youtube.com/watch?v=a5xnIAxihTk.

**Comment by infojunkie** [comment] 2018-08-15 18:59
I confirm that:
- logging out and refreshing the page does NOT attempt to automatically log back in
- I can logout and login again without error

**Comment by caiosba** [comment] 2018-08-15 19:00
Labeled as `pending test deployment`. Will close as soon as this is deployed to the test server and verified by QA people.

**Comment by caiosba** [comment] 2018-08-17 15:58
Deployed to QA, please verify.

**Comment by wafaaheikal** [comment] 2018-08-17 16:36
Verified

**Comment by caiosba** [comment] 2018-08-22 21:30
Verified on live :heavy_check_mark:

**Closed by caiosba** 2018-08-22 21:30 UTC
Labels: ready for production
